default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV["DB_POOL"] || 2 %>

development:
  <<: *default
  host: localhost
  database: async_development

test:
  <<: *default
  host: localhost
  database: async_test

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] %>
  checkout_timeout: 1
